package com.lordescanor.botforge;

import android.app.*; import android.os.*; import android.graphics.Color; import android.view.*; import android.widget.*;
import java.util.*; import java.io.File; import android.content.*; import android.net.Uri; import androidx.core.content.FileProvider;

public class CreateBotActivity extends Activity {
    LinearLayout box; Button next; TextView step; int page=1; BotProject bot=new BotProject(); ArrayList<DevRow> rows=new ArrayList<>();
    EditText name,nameAr,num,url,id;
    public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_create_bot);box=findViewById(R.id.stepContainer);next=findViewById(R.id.next);step=findViewById(R.id.step);next.setOnClickListener(v->{if(validate()){if(page<4){page++;render();}else generate();}});render();}
    TextView label(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(15);t.setPadding(4,16,4,6);return t;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(0xff9AA5B1);e.setSingleLine(true);e.setBackgroundResource(R.drawable.bg_input);e.setPadding(14,0,14,0);box.addView(e,new LinearLayout.LayoutParams(-1,56));return e;}
    void render(){box.removeAllViews();step.setText("الخطوة "+page+" من 4");next.setText(page==4?"إنشاء البوت وتصدير ZIP":"التالي");if(page==1)page1();else if(page==2)page2();else if(page==3)page3();else page4();next.setEnabled(true);}
    void page1(){box.addView(label("اسم البوت"));name=input("مثال: ORACLE BOT");name.setText(bot.name);box.addView(label("اسم البوت بالعربي"));nameAr=input("مثال: بوت أوراكل");nameAr.setText(bot.nameAr);box.addView(label("رقم البوت"));num=input("مثال: 2010xxxxxxxx");num.setText(bot.number);}
    void page2(){box.addView(label("المطورون"));if(rows.size()==0)rows.add(new DevRow());for(DevRow r:rows)addRowView(r);Button add=new Button(this);add.setText("+ إضافة مطور");add.setOnClickListener(v->{saveRows();rows.add(new DevRow());render();});box.addView(add);}
    void addRowView(DevRow r){box.addView(label("المطور "+(rows.indexOf(r)+1)+" — الرقم"));r.number=input("رقم المطور");r.number.setText(r.savedNumber);box.addView(label("اسم المطور"));r.name=input("الاسم");r.name.setText(r.savedName);box.addView(label("اسم المطور بالعربي"));r.nameAr=input("الاسم بالعربي");r.nameAr.setText(r.savedNameAr);Button del=new Button(this);del.setText("حذف هذا المطور");del.setOnClickListener(v->{saveRows();rows.remove(r);render();});box.addView(del);}
    void saveRows(){for(DevRow r:rows){if(r.number!=null)r.savedNumber=r.number.getText().toString();if(r.name!=null)r.savedName=r.name.getText().toString();if(r.nameAr!=null)r.savedNameAr=r.nameAr.getText().toString();}}
    void page3(){box.addView(label("رابط قناة الواتساب"));url=input("https://whatsapp.com/channel/...");url.setText(bot.channelUrl);box.addView(label("آيدي القناة (اختياري)"));id=input("120...@newsletter");id.setText(bot.channelId);}
    void page4(){box.addView(label("مراجعة قبل الإنشاء"));addReview("اسم البوت",bot.name);addReview("الاسم بالعربي",bot.nameAr);addReview("رقم البوت",bot.number);addReview("عدد المطورين",String.valueOf(bot.developers.size()));for(int i=0;i<bot.developers.size();i++){Developer d=bot.developers.get(i);addReview("المطور "+(i+1),d.name+" — "+d.number);}addReview("رابط القناة",bot.channelUrl);addReview("آيدي القناة",bot.channelId.isEmpty()?"اختياري — غير مضاف":bot.channelId);}
    void addReview(String k,String v){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(12,12,12,12);row.setBackgroundResource(R.drawable.bg_card);TextView t=new TextView(this);t.setText(k+"\n"+v);t.setTextColor(Color.WHITE);t.setTextSize(15);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button e=new Button(this);e.setText("✎");e.setOnClickListener(x->{if(page==4){saveAll();}page=keyPage(k);render();});row.addView(e);box.addView(row,new LinearLayout.LayoutParams(-1,-2));Space sp=new Space(this);box.addView(sp,new LinearLayout.LayoutParams(1,8));}
    int keyPage(String k){if(k.contains("اسم")||k.contains("رقم البوت"))return 1;if(k.contains("المطور"))return 2;return 3;}
    void saveAll(){if(name!=null){bot.name=name.getText().toString().trim();bot.nameAr=nameAr.getText().toString().trim();bot.number=num.getText().toString().trim();}saveRows();}
    boolean validate(){if(page==1){bot.name=name.getText().toString().trim();bot.nameAr=nameAr.getText().toString().trim();bot.number=num.getText().toString().trim();if(bot.name.isEmpty()||bot.nameAr.isEmpty()||bot.number.isEmpty()){toast("املأ بيانات البوت أولاً");return false;}}else if(page==2){saveRows();bot.developers.clear();for(DevRow r:rows){String a=r.savedNumber.trim(),b=r.savedName.trim(),c=r.savedNameAr.trim();if(a.isEmpty()||b.isEmpty()||c.isEmpty()){toast("اكمل بيانات كل مطور");return false;}bot.developers.add(new Developer(a,b,c));}}else if(page==3){bot.channelUrl=url.getText().toString().trim();bot.channelId=id.getText().toString().trim();if(bot.channelUrl.isEmpty()){toast("أدخل رابط القناة");return false;}}return true;}
    void generate(){saveAll();if(page==4&&bot.developers.size()==0){toast("لا يوجد مطور");return;}next.setEnabled(false);new Thread(()->{try{File f=BotGeneratorEngine.generate(this,bot);bot.zipPath=f.getAbsolutePath();new BotStore(this).add(bot);runOnUiThread(()->{next.setEnabled(true);new AlertDialog.Builder(this).setTitle("تم إنشاء البوت").setMessage("تم تجهيز ZIP بنجاح\n\n"+f.getAbsolutePath()).setPositiveButton("مشاركة / إرسال",(d,w)->{Intent s=new Intent(Intent.ACTION_SEND);s.setType("application/zip");Uri u=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);s.putExtra(Intent.EXTRA_STREAM,u);s.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(s,"إرسال ZIP"));}).setNegativeButton("إغلاق",null).show();});}catch(Exception e){runOnUiThread(()->{next.setEnabled(true);toast("حدث خطأ: "+e.getMessage());});}}).start();}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    static class DevRow{EditText number,name,nameAr;String savedNumber="",savedName="",savedNameAr="";}
}
